version: '3'
services:
  jupyter-1:
    image: parrthsarangi/jupyter:jupyter
    networks: 
      default:
        aliases:
          - net-jupyter
    build: .
    volumes: 
    - ${PWD}/workspace:/home/jovyan/workspace
  nginx:
    image: parrthsarangi/jupyter:nginx
    build: ./nginx
    ports:
    - 8888:8888 
    - 4040:4040
    